### ISSUE TITLE
this has been bothering me for a very long time, i dont think youll believe me.

### ISSUE THREAD

**Issue by GittyMuh** [relaxtakenotes/ssc#1]
this addon has been crashing my gmod for a while. i dont know why. i removed all my other movement mods to see if it was a conflicting issue. it wasnt. i tried removing all my addons. and i came to the conclusion that your mod is making gmod unstable cause its changing hardcoded movement scripts on the game itself. im not sure how to fix this but. i think it has to do something with arccw and tfa...

**Comment by GittyMuh** [comment]
hello???

**Comment by relaxtakenotes** [comment]
how come? nothing that i do in the code causes any crashes. there're no documented situations of that ever happening

**Comment by relaxtakenotes** [comment]
im fairly sure other people would've caught on too if that was the case

**Comment by GittyMuh** [comment]
> im fairly sure other people would've caught on too if that was the case

ever since i removed your addon my crashes stopped happening
idk what it was. ill test it again.

**Comment by GittyMuh** [comment]
maybe just maybe i didnt do menu_cleargmas or something else that was causing the conflicts to happen.
idk if thats possible
i verified gmod cache over 7 times in one day. still crashed.
im doing further testing ONCE MORE

**Comment by GittyMuh** [comment]
if i get an error/crash ill send you the crash message

**Comment by relaxtakenotes** [comment]
Send me a dmp file generated in the game directory I might wanna see if it has anything valuable for me

**Comment by GittyMuh** [comment]
wierd
now that i removed all my arccw and tfa addons and switched to TacRP and mw2019 base the addon is no longer causing my crashes... maybe it was the movement hook override thing that was causing my game to die..?
afterall the bug is fixed now.
im gonna close this issue untill another one happens.
