### ISSUE TITLE
i was right.

### ISSUE THREAD

**Issue by GittyMuh** [relaxtakenotes/ssc#2]
i installed tfa and some tfa weapons. roughly after playing for what seemed to be 6 MINUTES?!?!? the game crashed on me.
i removed tfa and the tfa weapons. ive been ingame for over 3 hours and no crashes.
your addon conflicts with weapon base movement modifiers causing fatal errors (hard crashes. closing the game)

**Comment by GittyMuh** [comment]
if no one else experiences these and all i can say is wow...
i dont have any other addons that could conflict

**Comment by GittyMuh** [comment]
ill also mention that i disabled override base weapon hooks

**Comment by GittyMuh** [comment]
this also conflicted with the doom/doom eternal swep packs.

**Comment by GittyMuh** [comment]
anything that changes the players movement speed (sweps that make you walk slower when doing something or holding it) makes this addon act up-

**Comment by GittyMuh** [comment]
i think its because the step speed + movement speed
if the player walks slower then the set speed to step speed or something THAT MAKES ABSOLUTELY NO SENSE
BUT IT KEEPS FUCKING UP MY GAME. thank you.

**Comment by relaxtakenotes** [comment]
give me the collection with the tfa weapons u use

**Comment by relaxtakenotes** [comment]
sorry for not responding for so long im just super busy with school

**Comment by relaxtakenotes** [comment]
closing it due to author not responding and no one else having this type of issue
